### PR TITLE
Fix for being stuck in catastrophic backtracking Resolves #399

### LINKED ISSUE #399: Thread stuck in split select detection regex
We recently encountered an unresponsive shard with its main thread stuck in a regex. Here's the relevant part of the threaddump:
https://hastebin.com/voqugexodu.txt

### PR DESCRIPTION
**Pull request by Shredder121**
Fixes #399 
So instead of using a regex, I propose a constant-time Splitter based approach.
(The `COMMA` splitter should also be reusable for other things)

### CODE REVIEW

**Comment by napstr** [comment]
Does this work on whitespace? Current behavior does + I find it much more convenient myself :upside_down_face:

File: FredBoat/src/main/java/fredboat/util/TextUtils.java [hunk 1]
```diff
@@ -44,16 +47,23 @@
...
 
 public class TextUtils {
 
     private static final Pattern TIMESTAMP_PATTERN = Pattern.compile("^(\\d?\\d)(?::([0-5]?\\d))?(?::([0-5]?\\d))?$");
 
     private static final List<Character> markdownChars = Arrays.asList('*', '`', '~', '_');
 
+    public static final Splitter COMMA = Splitter.on(',')
+            .omitEmptyStrings() // 1,,2 doesn't sound right
+            .trimResults();// have it nice and trim
```
Comment (Shredder121) [inline FredBoat/src/main/java/fredboat/util/TextUtils.java]: @napstr This does the whitespace handling.
it tokenizes on comma, so`1, 2, 3` => `1`,`<sp>2`,`<sp>3` get trimmed individually to `1`,`2`,`3`.

Comment (Shredder121) [reply FredBoat/src/main/java/fredboat/util/TextUtils.java]: O wait I c

File: FredBoat/src/main/java/fredboat/command/music/control/SelectCommand.java [hunk 2]
```diff
@@ -80,14 +80,7 @@ static void select(CommandContext context) {
...
             } else if (TextUtils.isSplitSelect(sanitizedQuery)) {
-                // Remove all non comma or number characters
-                String[] querySplit = sanitizedQuery.split(",|\\s");
-
-                for (String value : querySplit) {
-                    if (StringUtils.isNumeric(value)) {
-                        requestChoices.add(Integer.valueOf(value));
-                    }
-                }
+                requestChoices.addAll(TextUtils.getSplitSelect(sanitizedQuery));
```
Comment (napstr) [inline FredBoat/src/main/java/fredboat/command/music/control/SelectCommand.java]: The sanitized query (see method at the bottom of the SelectCommand class) needs to be adjusted for the rules of the matcher (specifically whitespaces), possibly even replaced/merged with it so there is only one place responsible.

Comment (Shredder121) [reply FredBoat/src/main/java/fredboat/command/music/control/SelectCommand.java]:
```java
@Test
void nonDigitsInSplitSelect() {
    Assertions.assertIterableEquals(
            Collections.singleton(1),
            TextUtils.getSplitSelect("We are number 1 but even this string matches")
    );
}
```
So are you saying this should match as well?
So when cleaning it up reduces it to just numbers, anything can be made a split select string?

Comment (Shredder121) [reply FredBoat/src/main/java/fredboat/command/music/control/SelectCommand.java]: I changed this to be heuristic based, if there is an awful lot of cleanup before it can be used as a split selection, it's not a split selection.
How does that sound?

**Comment by Shredder121** [comment]
In the selectcommand it filters out the numbers, didn't know if it needed to be there still.
Can also move that into the isSplitSelect check for more cleanup :clap:
So shall I do that?

**Comment by napstr** [comment]
If you think that's in scope for this PR sure. It's why I didn't merge right away, just in case it needs more than a line change.
